### ISSUE TITLE
error when word = "constructor"

### ISSUE THREAD

**Issue by monolithpl** [spencermountain/efrt#9]
please make a note in the readme that if there's the word "constructor" (a javascript reserved word) then you get strange errors (TypeError: h[val].push is not a function). either that or have the word filtered out automatically.
thanks for the great library, it's a massive improvement over Steve Hanov's work!

**Comment by spencermountain** [comment]
hey! I really appreciate that!
Looks like I need to add a few `hasOwnProperty()` calls. Will do it this week
cheers

**Comment by monolithpl** [comment]
great! it took me a while to figure out what was going wrong.
so impressed with the performance of your library i made a benchmark https://monolithpl.github.io/trie-compiler/

**Comment by spencermountain** [comment]
hey! that's awesome!
i think i got this working in [2.0.2](https://github.com/nlp-compromise/efrt/blob/913ddca302ac43ae9cc255a7efeb19b38b4fa551/test/reservedWords.test.js#L1) - check it out?

**Comment by spencermountain** [comment]
i put a link to that page on the readme. it's so great.
